USER_ID = 'c7f5wd69nvyx'
PAT = 'bd2bb298a58e4a04bd34c687a53a47c9'
APP_ID = 'storygenerator'
WORKFLOW_ID = 'Universal'
WORKFLOW_ID_TEXT = 'WORKFLOW-ID-TEXT'
WORKFLOW_ID_IMAGE = 'WORKFLOW-ID-IMAGE'
WORKFLOW_ID_STORY_GPT3 = 'WORKFLOW-ID-STORY-GPT4'

