USER_ID = 'c7f5wd69nvyx'
PAT = '050c907ca173481792e45325f4342c6b'
APP_ID = 'my-first-application-1393v'
WORKFLOW_ID = 'Universal'
WORKFLOW_ID_TEXT =  'Universal'
WORKFLOW_ID_IMAGE =  'Universal'
WORKFLOW_ID_STORY_GPT3 =  'Universal'

