USER_ID = 'c7f5wd69nvyx'
PAT = '2c2219e90d0d4536bef2ffdc76cb5796'
APP_ID = 'my-first-application-1393v'
WORKFLOW_ID =  'Universal'
WORKFLOW_ID_TEXT =  'Universal'
WORKFLOW_ID_IMAGE =  'Universal'
WORKFLOW_ID_STORY_GPT3 =  'Universal'

