USER_ID = 'c7f5wd69nvyx'
PAT = '96c0de1604964c90bedcedacb98c7165'
APP_ID = 'my-first-application-1393v'
WORKFLOW_ID = 'Universal'
WORKFLOW_ID_TEXT =  'Universal'
WORKFLOW_ID_IMAGE =  'Universal'
WORKFLOW_ID_STORY_GPT3 =  'Universal'

