USER_ID = 'c7f5wd69nvyx'
PAT = '535c6799623243aa86564558d2a368e7'
APP_ID = 'my-first-application-1393v'
WORKFLOW_ID = 'Universal'
WORKFLOW_ID_TEXT =  'Universal'
WORKFLOW_ID_IMAGE =  'Universal'
WORKFLOW_ID_STORY_GPT3 =  'Universal'

